version: '3'

services:
  bot:
    build: .
    volumes:
      - type: bind
        source: ./settings/data
        target: /app/settings/data
    stdin_open: true
    tty: true
    env_file: ./settings/.env
